### ISSUE TITLE
Define 'isochrones'

### ISSUE THREAD

**Issue by wcjochem** [riatelab/osrm#106]
In the readme, documentation and JOSS paper, please briefly define "isochrones" and "isometrics" to help users understand the outputs.

**Comment by JosiahParry** [comment]
I do not think this is resolved. I cannot find a definition of isochrone in the readme or various man pages. Though, I think the readme gets close at https://github.com/riatelab/osrm/blob/752a3ac9500f4f1895c4a137486a0fc31439841c/README.Rmd#L149.
