### ISSUE TITLE
How can I remove alternate routes when using osrm package in leaflet(r)?

### ISSUE THREAD

**Issue by Jorge-hercas** [riatelab/osrm#109]
Hello and thanks for reading me (and for this awesome package). I'm currently trying to create a map with a route for a source and destination address, but when I get the information from the OSRM service (with the package that connects to the website's API) it returns 2 possible routes and seems a bit confusing the map. I would like to eliminate the alternative route (or routes) and leave only one so that the map is as clear as possible, or if it is possible to put the alternative routes in another color, is it possible to do this?

The code im using is the following:

```
library(leaflet)
library(osrm)


df = data.frame(
  com =c("A","B"),
  lon =c(-99.10200,-99.13542),
  lat =c(19.45163,19.48500)
)



trips <- osrmTrip(df, returnclass="sf", overview = "full", osrm.profile = "car",
                  #options = list(alternatives = 0)
)

trip <- trips[[1]]$trip

leaflet(trip) |> 
  addProviderTiles(providers$CartoDB.DarkMatter, group = "OSM") %>% 
  addPolylines(
    opacity = 1,
    color = "#466180"
  ) |> 
  addCircleMarkers(lat = df$lat,
                   lng = df$lon,
                   popup = paste(df$com,"-",format(df$time,"%H:%M:%S")),
                   color = "red",
                   stroke = FALSE,
                   radius = 6,
                   fillOpacity = 1) 
```

I found in the official OSRM service documentation that the number of alternate paths can be configured:

![](https://i.stack.imgur.com/No5LT.png)

So maybe I could set it to 0, but so far I haven't found a way to implement that in the R package function, is that possible?

**Comment by rCarto** [comment]
The short answer is use `osrmRoute()` (it computes a route between points) instead of `osrmTrip()` (it computes the shortest trip between a set of points, route calculation + stops order). I'll update the documentation to make it more clear.
