### ISSUE TITLE
Speed parameter

### ISSUE THREAD

**Issue by fagnersutel** [riatelab/osrm#115]
What is the speed parameter in the osrmIsochrone.R file? In the walking parameter we have 10 * (1000/60)? Is it miles, kilometers/h?

**Comment by rCarto** [comment]
`speed` is expressed in meters per minute. For walking we use a theoretical value of 10 km/h, for driving 120 km/h.

This variable is used to get the theoretical maximum (euclidean) distance reached within the maximum `breaks` time value (and then compute a regular grid within this extent and return time distance in this grid, compute isopolygons etc.).

**Comment by fagnersutel** [comment]
Great, so if I want to make an isochron for kids around a school; is it possible to edit the osrmIsochrone.R file to adjust the walk to a factor that reduces this speed? Of course making a clone of the package.

**Comment by rCarto** [comment]
Nope, that would not be useful. This parameter only define the extent of the grid internally needed to get measures. If you want a custom speed (walking slowly, running...) to be used in time distance calculation by OSRM, you'll need to use your own instance of OSRM server and use a custom profile (editing a *.lua profile file from OSRM server GitHub repo for exemple) in it. 
osrm, the package, does not compute the time/distances measures, the OSRM server does.
