### ISSUE TITLE
 curl::curl_fetch_memory(utils::URLencode(url) => connection was reset

### ISSUE THREAD

**Issue by fjeuland** [riatelab/osrm#118]
I come here after asking [a question on osrm-backend](https://github.com/Project-OSRM/osrm-backend/issues/6461): could my problem be rather related to the use of R package?

Unless there is a particular configuration setup on the backend/server so that it can be requested from R?

King regards,

**Comment by rCarto** [comment]
Hello, 
There is no particular configuration to apply on the OSRM server to make it work with the package. 
But it is true that it is difficult to troubleshot this issue without knowing more about the server config. 
Have you tried to use a simpler example ? Something like : 
```r
library(osrm)
options(
  osrm.server = "http://server_adress with port (maybe?)/", 
  osrm.profile = "driving_or_car"
)
osrmTable(
  src = data.frame(x = 13.39, y = 52.52), 
  dst = data.frame(x = 13.385, y = 52.515)
)
osrmRoute(
  src = data.frame(x = 13.39, y = 52.52), 
  dst = data.frame(x = 13.385, y = 52.515)
)
```
Does any of this work?

 (You can send me the actual server address by mail if you want me to test it directly (my e-mail address is in the DESCRIPTION file of the package))

**Comment by fjeuland** [comment]
@rCarto , you kindly suggests to [slice the data](https://gist.github.com/rCarto/aa26b63ab9de12ab452038cd17e7c20b).

I encountered now a new error :

`> src <- st_centroid(COM)
> dst <- src
> dist1 <- osrmTable(src = src[1:10,c("lon", "lat")], 
+                    dst = dst[, c("lon", "lat")])
Error in `[.data.frame`(x, i, j, drop = drop) : 
  colonnes non définies sélectionnées`
  
  This should come from my original COM has a geometry column instead of lon & lat; I thus changed the code to :

`> dist1 <- osrmTable(src = src[1:10,c("geometry")], 
+                    dst = dst[, c("geometry)])
+ 
`
but the prompt seemed to wait for an other parameter (as the calculus doesn't start) or so ?

**Comment by rCarto** [comment]
You simply have a missing double quote ("). 
```r
dist1 <- osrmTable(src = src[1:10,c("geometry")], 
                              dst = dst[, c("geometry")])
```
\+ it would be a better practice to use `st_geometry()` instead of accessing the geom column name ("geometry"). Moreover this operation is not even needed as `osrmTable()` accepts sf object. This should work:  
```r
dist1 <- osrmTable(src = src[1:10, ], dst = dst)
```

**Comment by rCarto** [comment]
For the record the initial problem seems to be related to the config of OSRM server deployment (see https://github.com/Project-OSRM/osrm-backend/issues/1875).
A solution that does not imply modifying the server config would be to slice the `osrmTable()` calls, see the (over)simplified example [here](https://gist.github.com/rCarto/aa26b63ab9de12ab452038cd17e7c20b).
