### ISSUE TITLE
Duration of trip in osrmRoute and time of the day/traffic

### ISSUE THREAD

**Issue by ajo1993** [riatelab/osrm#126]
Hello 
I am trialling the great osrm package in R, using the demo server. I am using osrmRoute and I compare the distance and duration with GoogleMaps. Distance is very close to the GoogleMaps estimate while duration is usually at the bottom or below the range of GoogleMaps estimates.  
I was wondering if this is a function of traffic and if the osrmRoute result using the demo server is an average over the whole 24hr day? 

I checked the online documentation and the options in car.lua but I can't seem to find an option suggesting how duration is computed. Could you help me out?

Thanks a lot!

**Comment by rCarto** [comment]
Hello, 
You'll find a very similar issue here: https://github.com/riatelab/osrm/issues/88
cheers
