### ISSUE TITLE
Error using `osrmTable` with local server: long vectors not supported yet

### ISSUE THREAD

**Issue by emilphilipp** [riatelab/osrm#127]
Hi, thanks for the package!
I am trying to use the  `osrmTable` with a local server. The `loc` matrix contains 17261 longitude and latitude points:
```
osrmTable(loc ,measure = "duration",osrm.profile = "car",osrm.server = "http://0.0.0:5000/")
```
When I run this, I get the following error:
```
Error in rawToChar(r$content) : 
  long vectors not supported yet: /Volumes/Builds/R4/R-4.2.0/src/main/raw.c:68
```

**Comment by rCarto** [comment]
Hi, I can confirm this limitation. A solution would be to split the matrix into smaller chunks. 
Something like that:
![1713957879555](https://github.com/riatelab/osrm/assets/3041254/224e59c1-2079-4735-a520-77a070c7ff05)
