### ISSUE TITLE
Retry functionality?

### ISSUE THREAD

**Issue by neon-ninja** [riatelab/osrm#131]
Hi,

My colleague @jcol737 ran into this issue:

```R
Error in { : 
  task 22 failed - "Error in curl::curl_fetch_memory(utils::URLencode(url), handle = req_handle) : 
  Empty reply from server
"
```

This was caused by the OSRM server crashing due to running out memory. Docker automatically restarted it.

I considered submitting a PR to add in retry functionality (after a sleep, to allow for time for the server to come back up), but it looks like you already did, 4 years ago, in https://github.com/riatelab/osrm/commit/f4c8552c69c34e551d12042cce3b208d7e63788c. But then it was removed in https://github.com/riatelab/osrm/commit/c8dd46613c6aadc5339a3d4ad78827b1115ee22c. Why did you remove it? Would you consider adding it back in? Or should retry be the responsibility of the caller? Something like:

```R
r <- NULL
attempt <- 1
while( is.null(r) && attempt <= 3 ) {
  attempt <- attempt + 1
  tryCatch({
    r <- osrmTable(src = src, dst = dst, measure = c('duration','distance'))
  }, 
  error = function(cond) {
    message(conditionMessage(cond))
    Sys.sleep(60)
  })
}
```

**Comment by rCarto** [comment]
Hi, I don't remember exactly why I removed it (it seems to be a part of a larger refactoring ), but I still prefer to let the retry part be the responsibility of the caller as you suggest.
