### ISSUE TITLE
OSRM Map Matching Confidence > 1?

### ISSUE THREAD

**Issue by RiegelGestr** [riatelab/osrm#133]
Hi OSRM Team,

I’ve been working with the map matching service using some real-world trajectory data and have encountered an issue where the Confidence values returned exceed 1. For example, a recent request returned a confidence value of 4.
I understand that confidence values are generally expected to be within the range of 0 to 1, where higher values indicate a more accurate match to the road network. However, it seems that in certain cases, particularly with some input data, these values can exceed this expected range.
Could you provide clarification on how to interpret confidence values greater than 1? Is this a known issue, and are there any adjustments being considered in the algorithm to handle such occurrences?
Should I discard the matching or doing something different?
I found discussions on this topic in previous issues, like [Issue #6694](https://github.com/Project-OSRM/osrm-backend/issues/6694), which noted similar observations.

**Comment by rCarto** [comment]
This is the repo for the R package that links the OSRM engine to the R software. You should probably post the issue there https://github.com/Project-OSRM/osrm-backend
