### ISSUE TITLE
Fixed start/end trip points for one way trips

### ISSUE THREAD

**Issue by jonathangat** [riatelab/osrm#70]
Here there, many thanks for the great package. Is there any way to set fixed start/end trip points? The OSRM API service does provide these options - [see documentation here](http://project-osrm.org/docs/v5.10.0/api/#trip-service).

The cover photo of your repo shows a great example of a one way trip, I did take a look at [Timothée Giraud's tutorial](https://rgeomatic.hypotheses.org/854) but the `osrmViarouteGeom` function isn't available any more so I guess it might be a bit outdated (published in 2016).

Any ideas?
Cheers!

**Comment by rCarto** [comment]
Hello,
This feature is not implemented in `osrmTrip()` yet. We should add `source`, `destination` and `roundtrip` arguments. A PR would be welcomed.
The tutorial is outdated indeed. 
The cover photo uses `osrmRoute(loc = viapoints)`, the order of the points is predefined.

**Comment by rCarto** [comment]
I'll re-open the issue if someone is willing to make a PR.
