### ISSUE TITLE
The OSRM server returned an error: Error: object of type 'closure' is not subsettable

### ISSUE THREAD

**Issue by inesakr** [riatelab/osrm#78]
I tried to use the osrm package and the osrmTable function in R.  
I get an error (The OSRM server returned an error:
Error: object of type 'closure' is not subsettable) in this part of the code:  distancetable <-  osrm::osrmTable(src = ran_point_df, dst=pharmacy_df1). I used a public demo server and I still get an error. Can you help me? Thank you for your reply. 

library(osrm)
getOption("osrm.server")
pharmacy <- st_read("ljekarne.shp")
icon <- iconList(
  pharmacy_icons = makeIcon("symbol.png", iconWidth = 35, iconHeight = 35))

pharmacy_reproj <- st_transform(pharmacy, CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"))
plot(pharmacy_reproj, axes=T)
basicmap <- leaflet() %>% 
  addProviderTiles(providers$OpenStreetMap)%>%
  addMarkers(data= pharmacy_reproj,icon = icon, group = "Pharmacy")
lonmin <- 15.7720
lonmax <- 16.2353
latmin <- 45.5946
latmax <- 45.9298

n <- 100
set.seed(123)
ran_point <- tibble(id=1:n,
                         lon = runif(n, min = lonmin, max = lonmax),
                         lat = runif(n, min = latmin, max = latmax))

basicmap %>% 
  addCircleMarkers(data = ran_point, lng = ~lon, lat = ~lat, color = "red", radius = 6,
                   group = "Random points") %>% 
  addLayersControl(overlayGroups = c("Pharmacy", "Random points"))

ran_point_df <- as.data.frame(ran_point)
coord <- st_coordinates(pharmacy_reproj)
pharmacy_df <- as.data.frame(pharmacy_reproj)
pharmacy_df1 <- cbind(pharmacy_df,coord)
pharmacy_df1 <- pharmacy_df1[ , c("OBJECTID","X","Y")]
colnames(pharmacy_df1) <- c("id","lon","lat")
names(pharmacy_df1) <- c("id","lon","lat")
class(pharmacy_df1)
class(ran_point_df)

distancetable <-  osrm::osrmTable(src = ran_point_df, dst=pharmacy_df1)
Sys.time() - t0

**Comment by rCarto** [comment]
Hello, 
Have you tried the package examples? Do they work?
I can't tell you much more without a reproducible example.

**Comment by inesakr** [comment]
Hey, I solved my problem with Docker (like in this: https://ghanadatastuff.com/post/plotting_walking_distances_osrm/). Thanks for your reply. :)
