### ISSUE TITLE
Map title on osrmroute

### ISSUE THREAD

**Issue by geotrans** [riatelab/osrm#81]
Dear Authors,

I am following this tutorial on OSRM route, https://github.com/riatelab/osrm#osrmroute
Everything works for me except the fact that I am unable to add a title to the plot. I tried mf_title as suggested by mapsf documentation, but it did not help.  I also tried mf_layout but had no success. Could you suggest a solution or workaround for adding a title to these "route" plots? 

thank you.

**Comment by rCarto** [comment]
Hello, 
See the README file, I've updated the demo examples with the last versions of `mapsf` and `maptiles`.
