### ISSUE TITLE
Connection timed out after 10000 milliseconds

### ISSUE THREAD

**Issue by fabiolexcastro** [riatelab/osrm#82]
Hi, 

I have these problem: 

The OSRM server returned an error:
Error in open.connection(con, "rb"): Timeout was reached: [routing.openstreetmap.de] Connection timed out after 10000 milliseconds

I don't know whats is happening, I'm running this in the lastest version R, these is the tutorial. 

Best regards, 
Fabio Castro

**Comment by rCarto** [comment]
Can you try the last version of `osrm` (3.5.0, source from CRAN or GithHub)?
